name: CI/CD – Zyno Music Emotion App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports: [27017:27017]
        options: --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    ### FRONTEND SETUP ###
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend dependencies
      working-directory: ./Music-Recommendation-App
      run: npm ci

    - name: Build frontend (Next.js)
      working-directory: ./Music-Recommendation-App
      run: npm run build

    ### BACKEND SETUP ###
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install backend dependencies
      working-directory: ./Zyno/face_emotion_detection
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Flask app runs (optional test)
      working-directory: ./Zyno/face_emotion_detection
      run: |
        python -c "from backend import app; print('Flask backend loaded successfully')"
